version: 3

groups:
  protected:
    conditions:
    - >
      '*.md' in files or
      '*.html' in files or
      '*.yml' in files or
      '*.yaml' in files or
      '*.json' in files or
      'CNAME' in files or
      'config.js' in files or
      'index.js' in files or
      'webpack.config.js' in files or
      '*favicon*' in files
    - author.type != "bot"
    reviewers:
      users:
      - Minion3665
      teams:
      - beta-maintainers
    reviews:
      required: 2
      request: 1
      request_order: random
      author_value: 2

notifications:
- when: pull_request.opened
  comment: PR OPENED. Thanks @{{ author }}, we'll take it from here. (TYPE @{{ author.type }}, login TYPE @{{ author.login }}, ID @{{ author.id }})
